from recipes.almahelpers import fixsyscaltimes
__rethrow_casa_exceptions = True
h_init()
try:
    hifa_importdata(vis=['uid___A002_X86dcae_X416'], session=['session_1'])
    fixsyscaltimes(vis = 'uid___A002_X86dcae_X416.ms')
    fixplanets(vis = 'uid___A002_X86dcae_X416.ms', field = '2', fixuvw = T)
    h_save()
    h_init()
    hifa_importdata(vis=['uid___A002_X86dcae_X416'], session=['session_1'])
    hifa_flagdata(hm_tbuff='manual')
    hifa_fluxcalflag(pipelinemode="automatic")
    hif_refant(pipelinemode="automatic")
    hifa_tsyscal(pipelinemode="automatic")
    hifa_tsysflag(pipelinemode="automatic")
    hifa_wvrgcalflag(pipelinemode="automatic")
    hif_lowgainflag(pipelinemode="automatic")
    hif_setjy(pipelinemode="automatic")
    hif_bandpass(pipelinemode="automatic")
    hif_bpflagchans(pipelinemode="automatic")
    hifa_gfluxscale(pipelinemode="automatic")
    hifa_timegaincal(pipelinemode="automatic")
    hif_applycal(pipelinemode="automatic")
    hif_makecleanlist(intent='PHASE,BANDPASS,CHECK')
    hif_cleanlist(pipelinemode="automatic")
finally:
    h_save()
